name: Deploy Application

on:
  push:
    paths: 
      - 'kubernetes/**' 

jobs:
  tf_fmt:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
    - name: Configure Kubectl
      uses: azure/setup-kubectl@v3.0
      with:
        version: 'v1.29.2'
      id: install
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Update KubeConfig  
      run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }} --region=us-east-1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
            
    - name: eks app deployment
      run: cd kubernetes #&& kubectl apply -f deployment.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: eks public lb creation
      run : cd kubernetes #&& kubectl apply -f public-lb.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}   

    